id: P009360
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS16761
  title: སྤྱི་སྤུངས་གསང་བ་བསེན་ཐུབ་རྒྱུད།
  author: ''
  volumes:
    299f5ec814974ba38ac4522b79f6ab9c:
      image_group_id: I8LS16775
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
