id: I401CFA27
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T03:44:32+00:00'
last_modified: '2022-06-08T10:27:46.305986+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16761
  title: སྤྱི་སྤུངས་གསང་བ་བསེན་ཐུབ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1738':
      image_group_id: I8LS16775
      title: ''
      total_pages: 202
      order: 1
      base_file: 1738.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
